import java.io.PrintStream;
import java.util.ArrayList;
import java.util.List;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ptang' at '8/4/15 1:34 PM' with Gradle 2.5
 *
 * @author ptang, @date 8/4/15 1:34 PM
 */
public class Library {

    private PrintStream printStream;
    private List<Book> books;

//    //public Library() {
//        this(new ArrayList<Book>());
//    }

    public Library(List<Book> books, PrintStream printStream) {
        this.books = books;
        this.printStream = printStream;

    }


    public String open() {
        return "Welcome to the Library! Biblioteca is available!";
    }


    public void listAllBooks() {
        for (Book book : books) {
            printStream.println(book.toString());
        }


    }

    public void checkOutBook() {

    }

//    public void generateMenu() {
//
//    }
}
