import java.io.BufferedReader;
import java.io.IOException;
import java.io.PrintStream;
import java.util.List;

import static java.lang.Integer.parseInt;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ptang' at '8/4/15 1:34 PM' with Gradle 2.5
 *
 * @author ptang, @date 8/4/15 1:34 PM
 */
public class Library {

    private PrintStream printStream;
    private BufferedReader bufferedReader;
    private List<Book> books;

//    //public Library() {
//        this(new ArrayList<Book>());
//    }

    public Library(List<Book> books, PrintStream printStream, BufferedReader bufferedReader) {
        this.books = books;
        this.printStream = printStream;

        this.bufferedReader = bufferedReader;
    }


    public String open() {
        return "Welcome to the Library! Biblioteca is available!";
    }


    public void listAllBooks() {
        for (int i = 0; i < books.size(); i++) {
            Book currentBook = books.get(i);
            if (currentBook.isInLibrary()) {
                printStream.println((i + 1) + " | " + currentBook);
            }
        }


    }

    public void checkOutBook() {
        int bookID = getBookID();

        Book currentBook = getBookFromID(bookID);

        if (currentBook.isInLibrary()) {
            currentBook.checkOut();
            printStream.println("Thank you! Enjoy the book");
        } else {
            printStream.println("That book is not available.");
        }

    }

    private Book getBookFromID (int bookID) {
        Book currentBook = null;
        if (bookID < books.size()) {
            currentBook = books.get(bookID);
        }

        return currentBook;
    }

    private int getBookID() {
        printStream.println("Please enter the book ID:");
        String userInput = null;
        try {
            userInput = bufferedReader.readLine();
        } catch (IOException e) {
            e.printStackTrace();
        }

        int bookID = 0;
        try {
            bookID = parseInt(userInput) - 1;
        } catch (NumberFormatException e) {
            printStream.println("A number was not input");
        }
        return bookID;
    }

    public void returnBook() {
        int bookID = getBookID();

        Book currentBook = getBookFromID(bookID);
        currentBook.checkIn();
    }

    public void addBook(Book book1) {
        books.add(book1);
    }

//    public void generateMenu() {
//
//    }
}
