import org.junit.Before;
import org.junit.Test;

import java.io.PrintStream;
import java.util.ArrayList;
import java.util.List;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.*;
import static org.mockito.Mockito.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'ptang' at '8/4/15 1:34 PM' with Gradle 2.5
 *
 * @author ptang, @date 8/4/15 1:34 PM
 */
public class LibraryTest {
    private Library library;
    private List<Book> listOfBooks;
    private Console console;
    private PrintStream printStream;

    @Before
    public void setup() {
        printStream = mock(PrintStream.class);
        listOfBooks = new ArrayList<>();
        library = new Library(listOfBooks, printStream);
    }

    @Test
    public void shouldProduceWelcomeWhenOpen() {
        assertThat(library.open(), is("Welcome to the Library! Biblioteca is available!"));
    }

    @Test
    public void shouldListNothingWhenLibraryCreatedWithNoBooks() {
        library.listAllBooks();
        verifyZeroInteractions(printStream);
    }

    @Test
    public void shouldListAllBooksWhenLibraryCreatedWithBooks() {
        listOfBooks.add(mock(Book.class));
        listOfBooks.add(mock(Book.class));

        library.listAllBooks();
        verify(printStream, times(2)).println(anyString());
    }
//
//    @Test
//    public void shouldGenerateMenu() throws Exception {
//        console = mock(Console.class);
//
//        console.runLibrary();
//
//        verify(library).generateMenu();
//    }
}
